name: pro_bread_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.6.0
  intl: ^0.18.0
  logger: ^2.0.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.9
  animated_widgets: ^1.1.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  cupertino_onboarding: ^1.2.0
  flutter_screenutil: ^5.9.0
  pinput: ^4.0.0
  easy_localization: ^3.0.6
  carousel_slider: ^4.2.1
  pin_code_text_field: ^1.8.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter_gen:
   output: lib/core/resources/
   line_length: 80

flutter:
  uses-material-design: true

 
  assets:
    - assets/images/svg/
    - assets/images/png/ 
    - assets/fonts/ 

    
  


  fonts:
    - family: Teshrin
      fonts:
        - asset:  assets\fonts\TeshrinARLTRegular.ttf
          weight: 400      
            
        - asset:  assets\fonts\TeshrinARLTBold.ttf
          weight: 700        

    
        
