name: pro_bread_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.9
  animated_widgets: ^1.1.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  cupertino_onboarding: ^1.2.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter_gen:
   output: lib/core/resources/
   line_length: 80

flutter:

  uses-material-design: true

 
  assets:
    - assets/images/svg/
    - assets/images/png/ 

    
  

  
  fonts:
    # - family: Teshrin AR LT
    #   fonts:
    #     - asset:  assets\fonts\Teshrin AR+LT Regular.ttf
        
    # - family: Teshrin AR LT Bold
    #   fonts:
    #     - asset:  assets\fonts\Teshrin AR+LT Bold.ttf
        

    - family: SF Pro Text
      fonts:
        - asset:  assets\fonts\SF-Pro-Text-Semibold.ttf  
        
        
